services:
  app:
    image: ghcr.io/jrafaelca/healthcheck-server-node:latest
    build:
      context: .
      target: production
    pull_policy: always
    environment:
      HOST: ${HOST:-0.0.0.0}
      PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    restart: unless-stopped
